let words = {
  addition: "the process of adding of numbers",
  meeting: "Event in which people come together",
  number: "Math symbol used for counting",
  exchang: "The act of trading",
  canvas: "Piece of fabric for all painting",
  garden: "space for planting flower and plant ",
  pocket: "A bag for carray a small items",
  needle: "A thin and sharp metal pin",
  expert: "person with expensive knowledge",
  statement: "A declarion of somthing",
  second: "one-sixtieth of munite",
  library: "piace containing collection of books",
  taste: "Ability of tongue to detect flavour",
  field: "Area of land for farming activities",
  store: "Largr shop where goods are traded",
  friend: "Person other than a family mumber",
  comfort: "A pleasant feeling of relaxation ",
  air: "the invisible gaseous",
  idea: "a thought or suggestion",
  svg: "a vector image format",
  jepg: "a samll image format",
  search: "act to find somthing",
  banana: "yellow long curved fruit",
  mysql: "a relational database system",
  mysql: "a relational database system",
  python: "programing language",
  guitar: "a musical instrument",
  aim: "purpose or intentions",
  gold: "yellow precious metal",
};
